# dbt_project:
#   outputs:
#     dev:
#       account: OAMDBRI-OXC72527
#       database: STOCK_DB
#       password: tempPassword@123
#       role: ACCOUNTADMIN
#       schema: STAGING
#       threads: 1
#       type: snowflake
#       user: BHARADWAJ
#       warehouse: COMPUTE_WH
#   target: dev




dbt_project:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: OAMDBRI-OXC72527
      user: BHARADWAJ
      password: 'tempPassword@123' 
      role: ACCOUNTADMIN
      warehouse: COMPUTE_WH
      database: STOCK_DB
      schema: PUBLIC  # dbt will build tables here first
      threads: 1
      client_session_keep_alive: TRUE
